### PR TITLE
feat: implement correct responsive office images

### PR DESCRIPTION
**Pull request by luismeyer**

### CODE REVIEW

**Comment by Wandkleister** [comment]
Some of the images are too big, even after reducing their resolution. I.e. the Berlin pictures still sum up to more than 2.5MB on desktop.
We need to get those numbers down :-D So either we compress them on our own beforehand (with something like this https://compressor.io/), or we ask the designers to deliver smaller pictures.

**Comment by luismeyer** [comment]
i will talk to darlene about this. Maybe we should also consider lazy loading the images of the hidden locations. What do you think about that @Wandkleister ?

**Comment by Wandkleister** [comment]
> i will talk to darlene about this. Maybe we should also consider lazy loading the images of the hidden locations. What do you think about that @Wandkleister ?

Yes a lazyload for those things would be ideal!

**Review by timbru31 — APPROVED** [review]

**Comment by timbru31** [comment]
I'd vote to add lazy loading in a separate PR. Besides that, the browser is pretty good in finding which images to load first/what's below the fold.

**Comment by luismeyer** [comment]
@Wandkleister got images with half the resolution then before from Darlene and put them in.

@timbru31 Didn't see your comment. Lazy loading works now 😅

**Pull request merged**
