### PR TITLE
(OLD BRANCH) Feature: add cases overview page basic structure

### PR DESCRIPTION
**Pull request by oyershov**
https://github.com/sinnerschrader/sinnerschrader-reboot/pull/746

### CODE REVIEW

**Review by moritzbehnke — CHANGES_REQUESTED** [review]

**Comment by wheelmaker24** [comment]
We've tried to rebase this branch onto development but failed as too much has changed since then.
Let

I suggest on of the following options for this branch:

- rebase onto the current development branch (we failed, but maybe @evgenypastushek succeeeds)
- create a new branch from development and cherry-pick the relevant changes from here
- create a new branch from development and manually copy the relevant files from here

@evgenypastushek What do you think?

**Comment by evgenypastushek** [comment]
@wheelmaker24 
I’ve resolved all conflicts related to the “cases pages’ PR
Unfortunately I can’t build project locally now. Will check it as soon as I have time
(in some urgent case we may just revert my last commits)

**Comment by evgenypastushek** [comment]
@wheelmaker24 
here is new PR https://github.com/sinnerschrader/sinnerschrader-reboot/pull/746
This one can be closed

**Comment by wheelmaker24** [comment]
This is an old branch, we will use the new one instead: https://github.com/sinnerschrader/sinnerschrader-reboot/pull/746

**Pull request closed without merging**
